version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./dockerprueba:/app
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'northwind'
      MYSQL_USER: 'bdi'
      MYSQL_PASSWORD: 'pepe1234'
      MYSQL_ROOT_PASSWORD: 'pepe1234'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: 'pepe1234'
    depends_on:
      - db

volumes:
  mysql_data: